Repository Vidya-GM/Recipe_Generator, pull requests merged in 2025-06, with the labels that each got.

#28 Update generate page
  culinary_cloud_ai/applications/recipes/models.py
  culinary_cloud_ai/applications/recipes/templates/recipes/generate_combined.html
  culinary_cloud_ai/config/static/css/main.css
Labels: bug, enhancement

#30 Add 'delete' button for comment
  culinary_cloud_ai/applications/recipes/templates/recipes/recipe_detail.html
  culinary_cloud_ai/applications/recipes/urls.py
  culinary_cloud_ai/applications/recipes/views.py
Labels: enhancement

#32 Add home page styiling
  culinary_cloud_ai/applications/recipes/templates/recipes/home.html
  culinary_cloud_ai/applications/recipes/views.py
  culinary_cloud_ai/config/static/css/main.css
Labels: enhancement

#36 enhance user profile page
  culinary_cloud_ai/applications/recipe_user/templates/recipe_user/recipeuser_update.html
  culinary_cloud_ai/config/static/css/main.css
Labels: enhancement

#38 Add animation for recipe card
  culinary_cloud_ai/applications/recipes/templates/recipes/recipe_container.html
  culinary_cloud_ai/config/static/css/main.css
Labels: enhancement

#41 Add Notification feature
  culinary_cloud_ai/applications/recipe_user/apps.py
  culinary_cloud_ai/applications/recipe_user/context_processors.py
  culinary_cloud_ai/applications/recipe_user/signals.py
  culinary_cloud_ai/applications/recipe_user/templates/recipe_user/notification_list.html
  culinary_cloud_ai/applications/recipe_user/urls.py
  culinary_cloud_ai/applications/recipe_user/views.py
  culinary_cloud_ai/applications/recipes/templates/recipes/recipe_detail.html
  culinary_cloud_ai/config/settings/base.py
  culinary_cloud_ai/config/static/css/main.css
  culinary_cloud_ai/config/static/css/notifications.css
  culinary_cloud_ai/config/static/images/trash_can.svg
  culinary_cloud_ai/config/templates/base.html
Labels: enhancement

#46 Modify recipe page design/structure, prompt, permissions for buttons.
  culinary_cloud_ai/applications/recipes/templates/recipes/home.html
  culinary_cloud_ai/applications/recipes/templates/recipes/recipe_detail.html
  culinary_cloud_ai/applications/recipes/views.py
  culinary_cloud_ai/config/static/css/main.css
  culinary_cloud_ai/config/templates/base.html
Labels: bug, enhancement

#48 Add required login to generate recipe
  culinary_cloud_ai/applications/recipes/views.py
Labels: enhancement

#49 Fix bug related to notification about deleted comment
  culinary_cloud_ai/applications/__init__.py
  culinary_cloud_ai/applications/recipe_user/templates/recipe_user/notification_list.html
  culinary_cloud_ai/applications/recipe_user/views.py
  culinary_cloud_ai/applications/recipes/generators/prompts.py
Labels: bug

#50 Add like and comment symbol to my_recipes card
  culinary_cloud_ai/applications/recipe_user/templates/recipe_user/recipe_container.html
Labels: enhancement

#51 Add favicon icon, change project name, text on the home page
  culinary_cloud_ai/applications/recipes/templates/recipes/generate_combined.html
  culinary_cloud_ai/applications/recipes/templates/recipes/home.html
  culinary_cloud_ai/config/static/css/main.css
  culinary_cloud_ai/config/static/images/favicon.ico
  culinary_cloud_ai/config/templates/base.html
Labels: enhancement
